from typing import Any, Callable

class BackgroundScheduler:
    def __init__(self) -> None: ...
    def add_job(
        self, func: Callable[..., Any], trigger: str | None = None, **kwargs: Any
    ) -> Any: ...
    def start(self) -> None: ...
    def shutdown(self) -> None: ...
